version: 2.1

jobs:
  build-test-python:
    parameters:
      python_version:
        description: "Python version specified as X.Y.Z"
        type: string
      python_arch:
        description: "Python arch specified as x64 of x86"
        type: string
    working_directory: /work
    docker:
      - image: dockcross/linux-<< parameters.python_arch >>
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libffi-dev tcl-dev tk-dev liblzma-dev libbz2-dev
            sudo apt-get install -y libgdbm-dev libssl-dev libsqlite3-dev libreadline-dev
            sudo apt-get install -y libncursesw5-dev libdb-dev libgdbm-compat-dev
      - run:
         name: download dashboard scripts
         command: |
           git clone git://github.com/python-cmake-buildsystem/python-cmake-buildsystem --branch dashboard --depth 1 scripts
      - run:
         name: build and test
         command: |
           set -e
           ctest --timeout 360 -S /work/scripts/circle_dashboard.cmake -VV
         environment:
           PY_VERSION: << parameters.python_version >>

workflows:
    build-and-test:
      jobs:
        # 3.6.4
        - build-test-python:
            name: python-3.9.8-x64
            python_version: 3.9.8
            python_arch: x64


